### ISSUE TITLE
加入 authentication 機制

### ISSUE THREAD

**Issue by lyhcode** [monosparta/gohiking-server#2]
1. 先 fork 回自己的 git 帳號
2. 建一個 `feature/add-authentication-mechanism` 分支
3. 實作 Laravel 基礎 authentication 機制
4. 發 pull-request 回來 `monosparta/gohiking-server` repository

**Comment by BOBYZH** [comment]
https://github.com/TrunkStudio-Trainee-Taipei/gohiking-server/pull/1
已經完成，晚點發PR到主REPO

**Comment by BOBYZH** [comment]
與台中後端專案進度已經整併，且佈署完成：[https://gohiking-server.herokuapp.com](https://gohiking-server.herokuapp.com)
